# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Craig's Notes"
tagline:          from __past__ import tips
url:              http://www.craigsnotes.net
description:      "Notes and memory joggers with a focus on cyber security, tech, tools and other tasty nuggets."
paginate:         5
baseurl:          /
author:
  name:           Craig Balding
  url:            https://twitter.com/craigbalding
  email:          craig.balding@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/craigbalding/craigsnotes.net

gems: [jekyll-paginate]
# theme: jekyll-theme-dinky
